describe("home page categories section", () => {
  it("redirects to categories page with the correct filter for action games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="action-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Action")
  })
  it("redirects to categories page with the correct filter for indie games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="indie-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Indie")
  })
  it("redirects to categories page with the correct filter for rpg games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="rpg-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "RPG")
  })
  it("redirects to categories page with the correct filter for adventure games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="adventure-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Adventure")
  })
  it("redirects to categories page with the correct filter for strategy games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="strategy-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Strategy")
  })
  it("redirects to categories page with the correct filter for simulation games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="simulation-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Simulation")
  })
  it("redirects to categories page with the correct filter for puzzle games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="puzzle-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Puzzle")
  })
  it("redirects to categories page with the correct filter for platformer games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="platformer-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Platformer")
  })
  it("redirects to categories page with the correct filter for casual games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="casual-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Casual")
  })
  it("redirects to categories page with the correct filter for sports games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="sports-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Sports")
  })
  it("redirects to categories page with the correct filter for shooter games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="shooter-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Shooter")
  })
  it("redirects to categories page with the correct filter for racing games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="racing-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Racing")
  })
  it("redirects to categories page with the correct filter for massively multiplayer games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="massively multiplayer-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Massively+Multiplayer")
  })
  it("redirects to categories page with the correct filter for arcade games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="arcade-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Arcade")
  })

  it("redirects to categories page with the correct filter for card games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="card-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Card")
  })

  it("redirects to categories page with the correct filter for family games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="family-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Family")
  })

  it("redirects to categories page with the correct filter for fighting games when the button is clicked", () => {
    cy.visit("/")
    cy.get('[data-testid="fighting-category-button"]').click()
    cy.url().should("include", "/categories")
    cy.url().should("include", "genres")
    cy.url().should("include", "Fighting")
  })
  // it("redirects to categories page with the correct filter for educational games when the button is clicked", () => {
  //   cy.visit("/")
  //   cy.get('[data-testid="educational-category-button"]').click()
  //   cy.url().should("include", "/categories")
  //   cy.url().should("include", "genres")
  //   cy.url().should("include", "Educational")
  // })

  // it("redirects to categories page with the correct filter for dice games when the button is clicked", () => {
  //   cy.visit("/")
  //   cy.get('[data-testid="dice-category-button"]').click()
  //   cy.url().should("include", "/categories")
  //   cy.url().should("include", "genres")
  //   cy.url().should("include", "Dice")
  // })
})
